-- Create TABLE
CREATE TABLE COUNTRY_CATALOG (
  id INT(11) NOT NULL AUTO_INCREMENT,
  COUNTRY VARCHAR(150),
  CAPITAL VARCHAR(150),
  COUNTRY_CODE VARCHAR(150),
  ISO_CODES2 VARCHAR(150),
  ISO_CODES3 VARCHAR(150),
  POPULATION VARCHAR(150),
  AREA_KM2 VARCHAR(150),
  GDP_$USD VARCHAR(150),
  PRIMARY KEY (id)
);
DROP TABLE COUNTRY_CATALOG;
SELECT * FROM COUNTRY_CATALOG;

DELETE FROM COUNTRY_CATALOG;

-- Insert data
INSERT INTO COUNTRY_CATALOG VALUES (id, 'Afghanistan', 'LOS ANGELES INTL', 'United States', 'US', '123', 1, 5, 'weg');

INSERT INTO COUNTRY_CATALOG VALUES
  (id, 'Afghanistan', 'LOS ANGELES INTL', 'United States', 'US', '123', 1, 2, ''),
  (id, 'Afghanistan', 'LOS ANGELES INTL', 'United States', 'US', '123', 1, 4, 'weg'),
  (id, 'Afghanistan', 'LOS ANGELES INTL', 'United States', 'US', '123', 1, 5, 'weg');


INSERT INTO COUNTRY_CATALOG  VALUES (id, NULL, '', '', '', '', NULL , NULL, '');